# Generated by Django 4.2.10 on 2024-02-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0002_alter_party_managers_alter_partymember_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partymember",
            name="character_name",
            field=models.CharField(default="Placeholder", max_length=100),
        ),
    ]
