# Generated by Django 4.2.10 on 2024-02-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0003_alter_partymember_character_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partymember",
            name="character_name",
            field=models.CharField(default="name", max_length=100),
        ),
    ]
