# Generated by Django 4.2.10 on 2024-02-27 22:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0004_alter_partymember_character_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
