# Generated by Django 4.2.10 on 2024-02-28 05:25

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0004_alter_partymember_character_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="description",
            field=markdownx.models.MarkdownxField(default=""),
            preserve_default=False,
        ),
    ]
