name: "PR Checks"
on:
  pull_request:
    branches:
      - "main"
      - "develop"
      - "release/**"

jobs:
  style:
    name: "pre-commit Checks"
    runs-on: ubuntu-latest
    env:
      PY_VERSION: "3.11"
      POETRY_VERSION: "1.7.1"
    steps:
      - uses: actions/checkout@v4
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ env.POETRY_VERSION }}
      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          installer-parallel: true
      - name: Set up Python 3.11 on ubuntu-latest
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-interaction --with dev
      - uses: pre-commit/action@v3.0.1

  tests:
    name: "Unit Testing"
    needs: [ style ]
    runs-on: ubuntu-latest
    env:
      PY_VERSION: "3.11"
      POETRY_VERSION: "1.7.1"
      SECRET_KEY: "z1sr@98lg&8@jz)i2nhj0)ic7em-!_g*3o^b!!pit%q$=d+t5o"
      DJANGO_DEBUG: "True"
    steps:
      - uses: actions/checkout@v4
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ env.POETRY_VERSION }}
      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          installer-parallel: true
      - name: Set up Python 3.11 on ubuntu-latest
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Run tests
        run: poetry run python3 manage.py test --parallel

  docs:
    name: "Build Docs"
    needs: [ tests ]
    runs-on: ubuntu-latest
    env:
      POETRY_VERSION: "1.7.1"
    steps:
      - uses: actions/checkout@v4
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ env.POETRY_VERSION }}
      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          installer-parallel: true
      - name: Set up Python 3.11 on ubuntu-latest
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-interaction --with docs
      - name: Build HTML
        run: poetry run sphinx-build -W -a -E -b html docs/source/ docs/build/html
      - name: Upload sphinx artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/html/
